import { Platform, StyleSheet } from 'react-native';
import { scaleStyleKeysLayout, scaleStyleRecord } from '../theme/typography';

/** Legacy fallback height; prefer `useAppChrome().bottomNavHeight`. */
export const BOTTOM_NAV_HEIGHT = Platform.OS === 'ios' ? 86 : 74;

const baseStyleDefinitions = {
  container: {
    flex: 1,
    backgroundColor: '#111827',
  },
  gridOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: '#111827',
    opacity: 0.3,
  },
  topGlow: {
    position: 'absolute',
    top: -140,
    left: '20%',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(125,162,199,0.1)',
  },
  content: {
    paddingTop: 12,
    paddingHorizontal: 16,
    /** End padding only; tab stack already clears `bottomNav` via `tabStackLayer`. */
    paddingBottom: 16,
    flexGrow: 1,
    justifyContent: 'space-between',
    gap: 16,
    backgroundColor: '#111827',
  },
  mapScreen: {
    flex: 1,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 20,
    backgroundColor: '#111827',
  },
  resourcesScreen: {
    flex: 1,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 20,
    backgroundColor: '#111827',
  },
  /** Logs / alert timeline embedded in the home alert modal (no duplicate outer padding). */
  resourcesScreenModalEmbed: {
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 0,
    backgroundColor: 'transparent',
  },
  resourcesTitle: {
    color: '#f8fafc',
    fontSize: 29,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  resourcesSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 6,
    marginBottom: 4,
    fontWeight: '600',
    lineHeight: 20,
  },
  resourcesScroll: {
    flex: 1,
    marginTop: 10,
  },
  resourcesScrollContent: {
    paddingBottom: 20,
    gap: 12,
  },
  resourcesCard: {
    width: '100%',
    alignSelf: 'stretch',
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  resourcesTag: {
    fontSize: 11,
    letterSpacing: 0.85,
    fontWeight: '700',
    marginBottom: 6,
  },
  resourcesCardTitle: {
    color: '#f1f5f9',
    fontSize: 19,
    fontWeight: '700',
    letterSpacing: -0.2,
    marginBottom: 6,
  },
  resourcesCardBody: {
    color: '#cbd5e1',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '500',
  },
  logEventCard: {
    paddingVertical: 12,
  },
  logEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  logEventTime: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
  },
  logEventLevel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  logEventSource: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  mapTitle: {
    color: '#f8fafc',
    fontSize: 26,
    fontWeight: '700',
  },
  mapSubtitle: {
    color: '#9ca3af',
    fontSize: 14,
    marginTop: 4,
    marginBottom: 12,
  },
  mapLayerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
    marginBottom: 10,
  },
  mapLayerChip: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(15,23,42,0.32)',
  },
  mapLayerChipActive: {
    borderColor: 'rgba(59,130,246,0.75)',
    backgroundColor: 'rgba(59,130,246,0.25)',
  },
  mapLayerChipText: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '600',
  },
  mapLayerChipTextActive: {
    color: '#bfdbfe',
  },
  mapContainer: {
    flex: 1,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  map: {
    flex: 1,
  },
  mapRecenterBtn: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.7)',
    backgroundColor: 'rgba(15,23,42,0.86)',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapRecenterBtnText: {
    color: '#bfdbfe',
    fontSize: 14,
    fontWeight: '700',
  },
  mapFallbackCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: 14,
    padding: 16,
    backgroundColor: 'rgba(15,23,42,0.35)',
  },
  mapFallbackText: {
    color: '#cbd5e1',
    fontSize: 16,
    fontWeight: '600',
  },
  insightsScreen: {
    flex: 1,
    paddingBottom: 16,
    backgroundColor: '#111827',
  },
  insightsTitle: {
    color: '#f8fafc',
    fontSize: 29,
    fontWeight: '800',
    letterSpacing: -0.3,
    flexShrink: 1,
  },
  insightsTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 4,
  },
  insightsHealthStatusStack: {
    alignItems: 'flex-end',
    gap: 2,
    flexShrink: 0,
  },
  insightsHealthSyncMeta: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'right',
  },
  insightsHealthCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    flexShrink: 0,
  },
  insightsHealthCapsuleConnected: {
    backgroundColor: 'rgba(34,197,94,0.12)',
    borderColor: 'rgba(34,197,94,0.35)',
  },
  insightsHealthCapsuleDisconnected: {
    backgroundColor: 'rgba(239,68,68,0.1)',
    borderColor: 'rgba(239,68,68,0.32)',
  },
  insightsHealthCapsuleSyncing: {
    backgroundColor: 'rgba(234,179,8,0.14)',
    borderColor: 'rgba(234,179,8,0.4)',
  },
  insightsHealthCapsuleDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  insightsHealthCapsuleDotConnected: {
    backgroundColor: '#22c55e',
  },
  insightsHealthCapsuleDotDisconnected: {
    backgroundColor: '#ef4444',
  },
  insightsHealthCapsuleDotSyncing: {
    backgroundColor: '#eab308',
  },
  insightsHealthCapsuleSpinner: {
    width: 10,
    height: 10,
  },
  insightsHealthCapsuleText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  insightsHealthCapsuleTextConnected: {
    color: '#86efac',
  },
  insightsHealthCapsuleTextDisconnected: {
    color: '#f87171',
  },
  insightsHealthCapsuleTextSyncing: {
    color: '#fde047',
  },
  insightsStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  insightsHealthTagline: {
    flex: 1,
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  insightsHealthTaglineConnected: {
    color: '#86efac',
  },
  insightsTrendWindowRow: {
    marginTop: 14,
    marginBottom: 20,
    width: '100%',
  },
  insightsTrendWindowLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.9,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  insightsTrendWindowChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  insightsTrendWindowChip: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.45)',
    backgroundColor: 'rgba(15,23,42,0.35)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  insightsTrendWindowChipActive: {
    borderColor: 'rgba(56,189,248,0.65)',
    backgroundColor: 'rgba(14,165,233,0.15)',
  },
  insightsTrendWindowChipText: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '700',
  },
  insightsTrendWindowChipTextActive: {
    color: '#e0f2fe',
  },
  insightsStarredGalleryWrap: {
    marginTop: 16,
    marginBottom: 4,
    overflow: 'hidden',
  },
  insightsStarredGalleryScroll: {
    overflow: 'hidden',
  },
  insightsStarredGalleryPage: {
    overflow: 'hidden',
  },
  insightsStarredGalleryEmptyText: {
    color: '#94a3b8',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 2,
  },
  insightsStarredGalleryDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  insightsStarredGalleryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  insightsStarredGalleryDotActive: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  insightsSectionLabel: {
    marginTop: 18,
    marginBottom: 8,
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  insightsSearchPanel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(2,6,23,0.45)',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
    overflow: 'hidden',
    maxWidth: '100%',
  },
  healthConnectBtn: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.6)',
    backgroundColor: 'rgba(59,130,246,0.2)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    marginTop: 10,
  },
  healthConnectBtnDisabled: {
    opacity: 0.55,
  },
  healthConnectBtnText: {
    color: '#bfdbfe',
    fontSize: 16,
    fontWeight: '800',
  },
  healthErrorText: {
    color: '#fca5a5',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    fontWeight: '600',
  },
  insightsLlmPrimaryBtn: {
    marginTop: 8,
  },
  insightsLlmRegenerateWrap: {
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  insightsLlmRegenerateText: {
    color: '#93c5fd',
    fontSize: 16,
    fontWeight: '700',
  },
  quickMetricSearchInput: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    backgroundColor: 'rgba(15,23,42,0.55)',
    borderRadius: 12,
    color: '#e2e8f0',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    fontWeight: '600',
  },
  quickMetricSearchResults: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
    width: '100%',
    maxWidth: '100%',
    marginTop: 10,
    overflow: 'hidden',
  },
  insightsQuickToThemesDivider: {
    height: 1,
    backgroundColor: 'rgba(148,163,184,0.22)',
    width: '100%',
    marginTop: 16,
    marginBottom: 12,
  },
  quickMetricOptionChip: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.45)',
    backgroundColor: 'rgba(15,23,42,0.35)',
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 6,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  quickMetricOptionChipSpacing: {
    marginLeft: 6,
  },
  quickMetricOptionChipActive: {
    borderColor: 'rgba(96,165,250,0.75)',
    backgroundColor: 'rgba(59,130,246,0.3)',
  },
  quickMetricOptionText: {
    width: '100%',
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    minWidth: 0,
  },
  quickMetricOptionTextActive: {
    color: '#eff6ff',
  },
  insightsTabStack: {
    gap: 6,
  },
  insightsTabScroll: {
    marginTop: 8,
    marginBottom: 6,
  },
  insightsHubScroll: {
    flex: 1,
  },
  insightsHubScrollContent: {
    paddingTop: 12,
  },
  insightsMetricSectionsStack: {
    gap: 4,
    marginTop: 8,
    paddingBottom: 8,
  },
  insightsMetricSection: {
    marginTop: 16,
    gap: 10,
  },
  insightsMetricSectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  insightsMetricSectionAccent: {
    width: 4,
    borderRadius: 999,
    alignSelf: 'stretch',
    minHeight: 36,
  },
  insightsMetricSectionHeaderText: {
    flex: 1,
    gap: 2,
  },
  insightsMetricSectionTitle: {
    color: '#e2e8f0',
    fontSize: 18,
    fontWeight: '800',
  },
  insightsMetricSectionDivider: {
    height: StyleSheet.hairlineWidth,
    width: '100%',
    backgroundColor: 'rgba(148,163,184,0.22)',
    marginTop: 8,
  },
  insightsMetricSectionSubtitle: {
    color: '#94a3b8',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  insightsMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 8,
  },
  insightsMetricGridCell: {
    width: '48%',
    alignSelf: 'stretch',
  },
  insightsMetricCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 12,
    backgroundColor: 'rgba(15,23,42,0.32)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingLeft: 14,
    position: 'relative',
    overflow: 'hidden',
  },
  insightsMetricCardFill: {
    flex: 1,
  },
  insightsMetricCardPressed: {
    opacity: 0.88,
  },
  insightsMetricCardGreyedOut: {
    opacity: 0.42,
  },
  insightsMetricCardLabelGreyedOut: {
    color: '#64748b',
  },
  insightsMetricCardBand: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
  },
  insightsMetricCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  insightsMetricCardContentFill: {
    flex: 1,
  },
  insightsMetricCardIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.4)',
    flexShrink: 0,
  },
  insightsMetricCardStarBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.45)',
  },
  insightsMetricCardStarBtnActive: {
    borderColor: 'rgba(251,191,36,0.7)',
    backgroundColor: 'rgba(251,191,36,0.18)',
  },
  insightsMetricCardStarText: {
    color: '#94a3b8',
    fontSize: 16,
    lineHeight: 16,
    fontWeight: '700',
  },
  insightsMetricCardStarTextActive: {
    color: '#fcd34d',
  },
  insightsMetricCardLabel: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '800',
    flex: 1,
    lineHeight: 18,
  },
  insightsMetricCardPreview: {
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  insightsGroupCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    backgroundColor: 'rgba(15,23,42,0.32)',
    overflow: 'hidden',
    position: 'relative',
    paddingLeft: 10,
  },
  insightsGroupBand: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 10,
    height: 56,
    borderBottomRightRadius: 8,
  },
  insightsGroupHeader: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  insightsGroupHeaderText: {
    flex: 1,
    paddingRight: 10,
  },
  insightsGroupTitle: {
    color: '#e2e8f0',
    fontSize: 19,
    fontWeight: '700',
  },
  insightsGroupSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 19,
    marginTop: 2,
    fontWeight: '600',
  },
  insightsGroupChevron: {
    color: '#93c5fd',
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '700',
  },
  insightsGroupBody: {
    gap: 6,
    padding: 8,
  },
  insightsTabRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 12,
  },
  insightsTab: {
    width: '100%',
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    paddingLeft: 20,
    backgroundColor: 'rgba(15,23,42,0.32)',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  insightsTabMainPress: {
    flex: 1,
    justifyContent: 'center',
  },
  insightsSubTabBand: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 10,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    opacity: 0.95,
  },
  insightsTabStarBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.45)',
  },
  insightsTabStarBtnActive: {
    borderColor: 'rgba(251,191,36,0.7)',
    backgroundColor: 'rgba(251,191,36,0.18)',
  },
  insightsTabStarText: {
    color: '#fcd34d',
    fontSize: 20,
    lineHeight: 20,
    fontWeight: '700',
  },
  insightsTabActive: {
    borderColor: 'rgba(59,130,246,0.7)',
    backgroundColor: 'rgba(59,130,246,0.2)',
  },
  insightsTabText: {
    color: '#cbd5e1',
    fontSize: 20,
    fontWeight: '700',
  },
  insightsTabTextActive: {
    color: '#bfdbfe',
  },
  insightsTrendChartCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 16,
    padding: 16,
    backgroundColor: 'rgba(15,23,42,0.52)',
    overflow: 'hidden',
  },
  insightsCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 16,
    padding: 16,
    backgroundColor: 'rgba(15,23,42,0.52)',
    marginBottom: 12,
  },
  insightsCardEyebrow: {
    color: '#93c5fd',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  insightsCardTitle: {
    color: '#f8fafc',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  insightsCardSection: {
    color: '#93c5fd',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 6,
  },
  insightsCardSummary: {
    color: '#cbd5e1',
    fontSize: 17,
    lineHeight: 24,
    marginTop: 8,
  },
  insightsChartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  insightsChartUnit: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
  },
  insightsLineChartWrap: {
    marginTop: 10,
  },
  insightsLineChartHScroll: {
    flexGrow: 0,
  },
  insightsLineChartHScrollContent: {
    flexGrow: 0,
    paddingRight: 6,
  },
  insightsLineChartRangeLegend: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
    marginBottom: 2,
    letterSpacing: 0.2,
  },
  insightsLineChartAxisStrip: {
    position: 'relative',
    height: 50,
    marginTop: 4,
    marginBottom: 2,
  },
  insightsLineChartAxisTick: {
    position: 'absolute',
    top: 0,
    width: 54,
    alignItems: 'center',
  },
  insightsLineChartAxisValue: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '800',
  },
  insightsLineChartAxisDate: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  insightsLineLabelsRow: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  insightsLineLabelItem: {
    flex: 1,
    alignItems: 'center',
  },
  insightsLineLabelsRowDense: {
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
  },
  insightsLineLabelItemDense: {
    flex: 0,
    flexGrow: 0,
    flexShrink: 0,
  },
  insightsChartValue: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '800',
  },
  insightsChartLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  insightsChartValueDense: {
    fontSize: 11,
    fontWeight: '700',
  },
  insightsChartLabelDense: {
    fontSize: 10,
    fontWeight: '700',
    marginTop: 1,
  },
  insightsPromptCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 14,
    padding: 14,
    backgroundColor: 'rgba(15,23,42,0.4)',
  },
  insightsPromptText: {
    color: '#9ca3af',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  insightsDetailScreen: {
    flex: 1,
  },
  insightsDetailOverlay: {
    flex: 1,
    zIndex: 2,
  },
  insightsDetailScroll: {
    flex: 1,
  },
  insightsDetailScrollContent: {
    paddingTop: 12,
    paddingBottom: 18,
  },
  insightsDetailBody: {
    gap: 4,
  },
  insightsDetailHero: {
    marginTop: 4,
    marginBottom: 8,
    gap: 4,
  },
  insightsDetailHeroValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  insightsDetailHeroValue: {
    color: '#f8fafc',
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: -1,
    lineHeight: 52,
  },
  insightsDetailHeroUnit: {
    color: '#94a3b8',
    fontSize: 18,
    fontWeight: '700',
  },
  insightsDetailHeroContext: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
  },
  insightsHeartRateChartWrap: {
    marginBottom: 4,
  },
  insightsDetailChartWrap: {
    marginBottom: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(148,163,184,0.16)',
    gap: 6,
  },
  insightsDetailChartCaption: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  insightsDetailSpotNote: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    marginBottom: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(148,163,184,0.16)',
  },
  insightsHeartRatePanel: {
    gap: 8,
    marginBottom: 4,
  },
  insightsHeartRateHeroContext: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  insightsHeartRateDayNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  insightsHeartRateDayNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.28)',
    backgroundColor: 'rgba(15,23,42,0.35)',
  },
  insightsHeartRateDayNavBtnDisabled: {
    opacity: 0.35,
  },
  insightsHeartRateDayNavLabel: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '700',
  },
  insightsHeartRateHeroStack: {
    minHeight: 88,
    marginBottom: 4,
    justifyContent: 'center',
    gap: 4,
  },
  insightsHeartRateHeroValueStack: {
    minHeight: 52,
    justifyContent: 'center',
  },
  insightsHeartRateHeroValueSlot: {
    justifyContent: 'center',
  },
  insightsHeartRateHeroValueSlotAbsolute: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
  },
  insightsHeartRateHeroSlot: {
    gap: 4,
  },
  insightsHeartRateHeroSlotAbsolute: {
    ...StyleSheet.absoluteFillObject,
  },
  insightsHeartRateSwipeLabelStack: {
    minHeight: 22,
    marginBottom: 10,
    justifyContent: 'center',
  },
  insightsHeartRateSwipeLabel: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  insightsHeartRateSwipeLabelLayer: {
    textAlign: 'center',
  },
  insightsHeartRateSwipeViewport: {
    overflow: 'hidden',
  },
  insightsChartPeriodPicker: {
    flexDirection: 'row',
    alignSelf: 'center',
    gap: 4,
    padding: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(15,23,42,0.45)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.2)',
    marginBottom: 8,
  },
  insightsChartPeriodSegment: {
    minWidth: 32,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  insightsChartPeriodSegmentSelected: {
    backgroundColor: 'rgba(255,55,95,0.22)',
  },
  insightsChartPeriodSegmentText: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '800',
  },
  insightsChartPeriodSegmentTextSelected: {
    color: '#fecdd3',
  },
  insightsDetailSummary: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
    marginTop: 12,
  },
  insightsDetailOverview: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.28)',
    paddingTop: 16,
    marginBottom: 8,
  },
  insightsDetailOverviewTitle: {
    color: '#f8fafc',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.2,
    marginTop: 6,
  },
  insightsDetailOverviewSummary: {
    color: '#cbd5e1',
    fontSize: 17,
    lineHeight: 24,
    marginTop: 8,
  },
  insightsDetailLlmSection: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.28)',
    paddingTop: 16,
    marginTop: 4,
  },
  insightsDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  insightsBackBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(2,6,23,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightsDetailHeaderText: {
    flex: 1,
  },
  insightsDetailSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 4,
    fontWeight: '600',
  },
  insightsMetricDescriptionWrap: {
    marginTop: 16,
    paddingTop: 16,
    paddingHorizontal: 2,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.22)',
    gap: 12,
  },
  insightsMetricInfoBlock: {
    gap: 4,
  },
  insightsMetricSectionLabel: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  insightsMetricDescription: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  insightsHeartHub: {
    marginTop: 4,
    gap: 16,
  },
  insightsHeartHubSection: {
    gap: 8,
  },
  insightsHeartHubSectionLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  insightsHeartHubRows: {
    gap: 0,
  },
  insightsHeartHubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    gap: 12,
  },
  insightsHeartHubRowPressable: {
    paddingHorizontal: 10,
    marginHorizontal: -10,
    borderRadius: 10,
  },
  insightsHeartHubRowSelected: {
    backgroundColor: 'rgba(125,162,199,0.14)',
  },
  insightsHeartHubRowPressed: {
    opacity: 0.88,
  },
  insightsHeartHubRowLabelSelected: {
    color: '#bfdbfe',
  },
  insightsHeartHubRowNumberSelected: {
    color: '#dbeafe',
  },
  insightsHeartHubRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.16)',
  },
  insightsHeartHubRowGreyedOut: {
    opacity: 0.42,
  },
  insightsHeartHubRowLabelGreyedOut: {
    color: '#64748b',
  },
  insightsHeartHubRowNumberGreyedOut: {
    color: '#64748b',
  },
  insightsHeartHubRowUnitGreyedOut: {
    color: '#475569',
  },
  insightsHeartHubRowText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  insightsHeartHubRowLabel: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  insightsHeartHubRowMeta: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  insightsHeartHubRowValue: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexShrink: 0,
  },
  insightsHeartHubRowNumber: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  insightsHeartHubRowUnit: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '700',
    marginLeft: 4,
  },
  insightsMetricCardSubtitle: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  goalsScreen: {
    flex: 1,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingBottom: 20,
    backgroundColor: '#111827',
  },
  goalsTitle: {
    color: '#f8fafc',
    fontSize: 29,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  goalsSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 4,
    fontWeight: '600',
  },
  goalsTabRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    marginBottom: 14,
  },
  goalsTab: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.32)',
  },
  goalsTabActive: {
    borderColor: 'rgba(125,162,199,0.86)',
    backgroundColor: 'rgba(125,162,199,0.28)',
  },
  goalsTabText: {
    color: '#a3b2c8',
    fontSize: 14,
    fontWeight: '700',
  },
  goalsTabTextActive: {
    color: '#dbeafe',
  },
  goalsScroll: {
    flex: 1,
  },
  goalsScrollContent: {
    gap: 10,
    paddingBottom: 24,
  },
  goalsEmptyText: {
    textAlign: 'center',
    marginTop: 8,
  },
  wellnessScreen: {
    flex: 1,
    paddingTop: 8,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: '#111827',
  },
  wellnessCentered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  wellnessScroll: {
    flex: 1,
  },
  wellnessIntroContent: {
    gap: 14,
    paddingBottom: 28,
  },
  wellnessIntroInstructions: {
    color: '#f8fafc',
    fontSize: 17,
    lineHeight: 26,
    fontWeight: '600',
  },
  wellnessResultsContent: {
    gap: 12,
    paddingBottom: 28,
  },
  wellnessTitle: {
    color: '#f8fafc',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  wellnessBody: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
  },
  wellnessHint: {
    color: '#94a3b8',
    fontSize: 13,
    lineHeight: 18,
  },
  wellnessResumeCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.28)',
    backgroundColor: 'rgba(15,23,42,0.45)',
    padding: 14,
    gap: 8,
  },
  wellnessResumeTitle: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '700',
  },
  wellnessPrimaryBtn: {
    borderRadius: 12,
    backgroundColor: '#7DA2C7',
    paddingVertical: 14,
    alignItems: 'center',
  },
  wellnessPrimaryBtnText: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  wellnessSecondaryBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    paddingVertical: 13,
    alignItems: 'center',
  },
  wellnessSecondaryBtnText: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '700',
  },
  wellnessQuestionHeader: {
    gap: 10,
    marginBottom: 8,
  },
  wellnessProgressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(148,163,184,0.22)',
    overflow: 'hidden',
  },
  wellnessProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#7DA2C7',
  },
  wellnessQuestionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  wellnessBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  wellnessQuestionContent: {
    gap: 18,
    paddingBottom: 24,
  },
  wellnessQuestionText: {
    color: '#f8fafc',
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '700',
  },
  wellnessAnswerList: {
    gap: 10,
  },
  wellnessAnswerBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.28)',
    backgroundColor: 'rgba(15,23,42,0.35)',
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  wellnessAnswerBtnSelected: {
    borderColor: 'rgba(125,162,199,0.9)',
    backgroundColor: 'rgba(125,162,199,0.22)',
  },
  wellnessAnswerBtnText: {
    color: '#cbd5e1',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  wellnessAnswerBtnTextSelected: {
    color: '#f8fafc',
  },
  wellnessInsightCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.22)',
    backgroundColor: 'rgba(15,23,42,0.35)',
    padding: 14,
    gap: 6,
  },
  wellnessInsightTitle: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '800',
  },
  wellnessFacetRow: {
    marginTop: 8,
    paddingLeft: 4,
    gap: 2,
  },
  wellnessDisclaimer: {
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  goalsCard: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.22)',
    borderRadius: 16,
    padding: 15,
    marginBottom: 12,
    backgroundColor: 'rgba(15,23,42,0.78)',
  },
  goalsCommunityCard: {
    overflow: 'hidden',
    padding: 0,
  },
  goalsCommunityCardImage: {
    width: '100%',
    height: 112,
    backgroundColor: 'rgba(30,41,59,0.95)',
  },
  goalsCommunityCardBody: {
    padding: 15,
  },
  challengeCommunityCard: {
    borderColor: 'rgba(59,130,246,0.42)',
    backgroundColor: 'rgba(30,58,138,0.3)',
  },
  challengePersonalCard: {
    borderColor: 'rgba(124,184,155,0.42)',
    backgroundColor: 'rgba(24,59,47,0.38)',
  },
  challengeHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  challengeTypeBadge: {
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    overflow: 'hidden',
  },
  challengeTypeCommunity: {
    color: '#93c5fd',
    borderColor: 'rgba(96,165,250,0.7)',
    backgroundColor: 'rgba(30,64,175,0.45)',
  },
  challengeTypePersonal: {
    color: '#d1fae5',
    borderColor: 'rgba(124,184,155,0.68)',
    backgroundColor: 'rgba(38,84,67,0.52)',
  },
  challengeFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: 'transparent',
    padding: 0,
    marginBottom: 14,
    gap: 8,
  },
  challengeFilterTab: {
    minWidth: 88,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.3)',
    backgroundColor: 'rgba(15,23,42,0.65)',
    paddingVertical: 7,
    paddingHorizontal: 12,
  },
  challengeFilterTabActive: {
    backgroundColor: 'rgba(59,130,246,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(96,165,250,0.65)',
  },
  challengeFilterText: {
    color: '#9fb0c7',
    fontSize: 14,
    fontWeight: '700',
  },
  challengeFilterTextActive: {
    color: '#e2e8f0',
  },
  challengeSummaryCard: {
    borderWidth: 1,
    borderColor: 'rgba(125,162,199,0.28)',
    borderRadius: 14,
    backgroundColor: 'rgba(30,41,59,0.82)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
  },
  challengeSummaryTitle: {
    color: '#dbeafe',
    fontSize: 16,
    fontWeight: '700',
  },
  challengeSummaryText: {
    color: '#a8b6cc',
    fontSize: 13,
    marginTop: 4,
  },
  challengeMembersPill: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: 'rgba(96,165,250,0.35)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: 'rgba(30,64,175,0.28)',
  },
  challengeChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  challengeChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(124,184,155,0.45)',
    backgroundColor: 'rgba(38,84,67,0.42)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  challengeChipMuted: {
    borderColor: 'rgba(148,163,184,0.35)',
    backgroundColor: 'rgba(15,23,42,0.7)',
  },
  challengeChipText: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '700',
  },
  createPersonalChallengeBtn: {
    borderWidth: 1,
    borderColor: 'rgba(124,184,155,0.4)',
    backgroundColor: 'rgba(38,84,67,0.5)',
    borderRadius: 13,
    paddingVertical: 11,
    alignItems: 'center',
    marginBottom: 12,
  },
  createPersonalChallengeBtnText: {
    color: '#d1fae5',
    fontSize: 14,
    fontWeight: '700',
  },
  challengeModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,23,0.68)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  challengeModalCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(15,23,42,0.98)',
    padding: 14,
  },
  createPostKeyboardAvoiding: {
    width: '100%',
  },
  challengeModalTitle: {
    color: '#f8fafc',
    fontSize: 19,
    fontWeight: '700',
  },
  challengeModalHint: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 4,
    marginBottom: 10,
  },
  challengeInput: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    color: '#e2e8f0',
    fontSize: 16,
    marginBottom: 10,
    backgroundColor: 'rgba(2,6,23,0.4)',
  },
  challengeInputMultiline: {
    minHeight: 78,
    textAlignVertical: 'top',
  },
  challengeModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  challengeModalCancelBtn: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  challengeModalCancelText: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '700',
  },
  challengeModalCreateBtn: {
    borderWidth: 1,
    borderColor: 'rgba(124,184,155,0.62)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(38,84,67,0.56)',
  },
  challengeModalCreateText: {
    color: '#d1fae5',
    fontSize: 14,
    fontWeight: '700',
  },
  goalsCardTitle: {
    color: '#f1f5f9',
    fontSize: 18,
    fontWeight: '700',
  },
  goalsCardDetail: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 4,
    lineHeight: 20,
  },
  goalsCardMeta: {
    color: '#9ccfc7',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 8,
  },
  goalCreateSection: {
    marginTop: 8,
    marginBottom: 12,
    gap: 10,
  },
  goalCreateSectionTitle: {
    fontSize: 16,
  },
  goalCreateHint: {
    marginTop: 0,
  },
  goalPeriodRow: {
    flexDirection: 'row',
    gap: 8,
  },
  goalTargetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  goalTargetInput: {
    flex: 1,
    marginBottom: 0,
  },
  goalTargetInputWide: {
    flex: 1,
    marginBottom: 0,
  },
  goalTargetDash: {
    marginTop: 0,
  },
  goalTargetUnit: {
    marginTop: 0,
    minWidth: 48,
  },
  goalCreatePreview: {
    marginTop: 0,
  },
  goalCreateBtnDisabled: {
    opacity: 0.45,
  },
  medSummaryCard: {},
  medSummaryCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  medSummaryTextBlock: {
    flex: 1,
    gap: 2,
  },
  medSummaryPreview: {
    marginTop: 0,
    fontSize: 12,
    lineHeight: 16,
  },
  medDetailRoot: {
    gap: 10,
    paddingBottom: 24,
  },
  medDetailSubtitle: {
    marginTop: 0,
  },
  medDosePeriodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  medDosePeriodChip: {
    flexGrow: 0,
    flexShrink: 0,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.32)',
  },
  medChecklistGroup: {
    gap: 6,
  },
  medChecklistGroupTitle: {
    fontSize: 15,
    marginTop: 2,
  },
  medChecklistGroupCard: {
    marginBottom: 0,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  medChecklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
  },
  medChecklistRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.15)',
  },
  medChecklistRowText: {
    flex: 1,
    gap: 2,
  },
  medChecklistMedName: {
    fontSize: 16,
  },
  medChecklistMeta: {
    marginTop: 0,
    fontSize: 13,
  },
  medManageSection: {
    marginTop: 4,
    gap: 6,
  },
  medManageCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 0,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  medManageCardBody: {
    flex: 1,
    gap: 2,
  },
  medManageActions: {
    flexDirection: 'row',
    gap: 4,
  },
  medManageActionBtn: {
    padding: 8,
  },
  medCalendarCard: {
    padding: 12,
    gap: 8,
  },
  medCalendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  medCalendarNavBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  medCalendarNavText: {
    fontSize: 28,
    lineHeight: 30,
    fontWeight: '300',
  },
  medCalendarMonthLabel: {
    fontSize: 16,
    fontWeight: '600',
  },
  medCalendarWeekdayRow: {
    flexDirection: 'row',
  },
  medCalendarWeekday: {
    flex: 1,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  medCalendarWeekRow: {
    flexDirection: 'row',
  },
  medCalendarDayCell: {
    flex: 1,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    margin: 2,
    gap: 2,
  },
  medCalendarDayCellSelected: {
    backgroundColor: '#E8A87C',
  },
  medCalendarDayCellToday: {
    borderWidth: 1,
    borderColor: '#E8A87C',
  },
  medCalendarDayNum: {
    fontSize: 14,
    fontWeight: '600',
  },
  medCalendarDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  medDayPanel: {
    padding: 12,
    gap: 8,
  },
  medDayPanelTitle: {
    marginBottom: 2,
  },
  medDayAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  medDayAddInput: {
    marginBottom: 0,
  },
  medScheduleFormTitle: {
    marginTop: 8,
    marginBottom: 4,
  },
  medScheduleBtn: {
    marginTop: 4,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  medScheduleBtnText: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  medChecklistToggle: {
    paddingRight: 4,
  },
  challengeProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
  },
  challengeProgressTrack: {
    flex: 1,
    height: 7,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(148,163,184,0.18)',
  },
  challengeProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#60a5fa',
  },
  challengeProgressLabel: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
    minWidth: 30,
    textAlign: 'right',
  },
  challengeCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  challengeQuickActionBtn: {
    borderWidth: 1,
    borderColor: 'rgba(96,165,250,0.45)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(37,99,235,0.22)',
  },
  challengeQuickActionText: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '700',
  },
  challengeDetailBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,23,0.72)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  challengeDetailModal: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.3)',
    backgroundColor: 'rgba(15,23,42,0.97)',
    padding: 14,
  },
  challengeDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  challengeDetailTitle: {
    color: '#e2e8f0',
    fontSize: 19,
    fontWeight: '700',
  },
  challengeDetailCloseBtn: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
  },
  challengeDetailCloseText: {
    color: '#cbd5e1',
    fontSize: 22,
    lineHeight: 24,
  },
  challengeDetailChips: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  challengeDetailName: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '700',
  },
  challengeDetailText: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 6,
    marginBottom: 8,
  },
  challengeDetailActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 10,
  },
  challengeDetailDismissBtn: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  challengeDetailDismissText: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '700',
  },
  challengeDetailPrimaryBtn: {
    borderWidth: 1,
    borderColor: 'rgba(96,165,250,0.55)',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(37,99,235,0.28)',
  },
  challengeDetailPrimaryText: {
    color: '#dbeafe',
    fontSize: 14,
    fontWeight: '700',
  },
  challengeTimelineRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: 10,
  },
  challengeTimelineRail: {
    width: 26,
    alignItems: 'center',
    paddingTop: 8,
  },
  challengeTimelineNode: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 2,
    backgroundColor: '#0f172a',
  },
  challengeTimelineNodeCommunity: {
    borderColor: '#60a5fa',
  },
  challengeTimelineNodePersonal: {
    borderColor: '#7cb89b',
  },
  challengeTimelineLine: {
    width: 2,
    flex: 1,
    marginTop: 4,
    backgroundColor: 'rgba(148,163,184,0.25)',
  },
  challengeTimelineContent: {
    flex: 1,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  challengeTimelineContentCommunity: {
    backgroundColor: 'transparent',
  },
  challengeTimelineContentPersonal: {
    backgroundColor: 'transparent',
  },
  communitySearchBar: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 13,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 14,
    backgroundColor: 'rgba(10,14,24,0.72)',
  },
  communitySearchText: {
    color: '#6b7280',
    fontSize: 14,
    fontWeight: '600',
  },
  communitySectionTitle: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 12,
  },
  communityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
    paddingBottom: 6,
  },
  communityCard: {
    width: '48%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(10,14,24,0.8)',
    padding: 0,
    overflow: 'hidden',
    minHeight: 210,
    flexDirection: 'column',
  },
  communityCardImage: {
    width: '100%',
    height: 100,
    backgroundColor: 'rgba(30,41,59,0.95)',
  },
  communityCardBody: {
    flex: 1,
    padding: 14,
    flexDirection: 'column',
  },
  communityCardTextBlock: {
    flexShrink: 0,
  },
  communityCardButtonSpacer: {
    flexGrow: 1,
    flexShrink: 0,
    minHeight: 18,
  },
  communityCardTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 29,
  },
  communityCardMeta: {
    color: '#cbd5e1',
    fontSize: 13,
    marginTop: 4,
  },
  communityJoinBtn: {
    flexShrink: 0,
    alignSelf: 'stretch',
    backgroundColor: '#7CB89B',
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
  },
  communityJoinBtnJoined: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: 'rgba(148,163,184,0.55)',
  },
  communityJoinText: {
    color: '#0f2a22',
    fontSize: 14,
    fontWeight: '800',
  },
  communityJoinTextJoined: {
    color: '#94a3b8',
    fontWeight: '700',
  },
  communityHero: {
    borderRadius: 18,
    height: 178,
    backgroundColor: 'rgba(31,41,55,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    padding: 14,
    marginBottom: 14,
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  communityHeroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  communityHeroScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(3, 7, 18, 0.5)',
  },
  communityHeroActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  communityHeroIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(3,7,18,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  communityHeroIconText: {
    color: '#f8fafc',
    fontSize: 19,
    fontWeight: '800',
  },
  communityHeroTag: {
    color: '#d1fae5',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  communitySettingsMenuRoot: {
    flex: 1,
  },
  communitySettingsMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.32)',
  },
  communitySettingsMenu: {
    position: 'absolute',
    borderRadius: 12,
    backgroundColor: 'rgba(15,23,42,0.97)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    overflow: 'hidden',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
  },
  communitySettingsMenuRow: {
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  communitySettingsMenuRowText: {
    color: '#fca5a5',
    fontSize: 18,
    fontWeight: '600',
  },
  communityDetailCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 18,
    backgroundColor: 'rgba(10,14,24,0.82)',
    padding: 16,
    marginBottom: 14,
  },
  communityDetailTitle: {
    color: '#f8fafc',
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '800',
  },
  communityDetailMeta: {
    color: '#d1d5db',
    fontSize: 17,
    marginTop: 6,
    fontWeight: '600',
  },
  communityDetailSub: {
    color: '#cbd5e1',
    fontSize: 17,
    marginTop: 8,
    marginBottom: 12,
  },
  communityActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  communityActionItem: {
    width: 64,
    alignItems: 'center',
  },
  communityActionIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(30,41,59,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityActionIconBtnActive: {
    borderColor: 'rgba(125,162,199,0.72)',
    backgroundColor: 'rgba(125,162,199,0.22)',
  },
  communityActionIcon: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '700',
  },
  communityActionLabel: {
    color: '#cbd5e1',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 6,
    fontWeight: '600',
  },
  communityOverviewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  communityOverviewPopup: {
    width: '100%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: 'rgba(124,184,155,0.45)',
    borderRadius: 14,
    backgroundColor: 'rgba(10,20,18,0.96)',
    padding: 14,
  },
  communityOverviewPopupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  communityOverviewPopupTitle: {
    color: '#d1fae5',
    fontSize: 17,
    fontWeight: '800',
  },
  communityOverviewCloseBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityOverviewCloseText: {
    color: '#e2e8f0',
    fontSize: 19,
    lineHeight: 22,
    fontWeight: '700',
  },
  communityOverviewPopupText: {
    color: '#dbe7e3',
    fontSize: 14,
    lineHeight: 22,
  },
  inviteContactsList: {
    maxHeight: 320,
  },
  inviteContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 10,
    gap: 10,
  },
  inviteContactInfo: {
    flex: 1,
  },
  inviteContactName: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  inviteContactPhone: {
    color: '#9ca3af',
    fontSize: 13,
    marginTop: 2,
  },
  inviteContactBtn: {
    borderRadius: 999,
    backgroundColor: '#7CB89B',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  inviteContactBtnText: {
    color: '#0f2a22',
    fontSize: 13,
    fontWeight: '800',
  },
  progressBoardTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
    marginTop: 4,
  },
  progressBoardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  createPostBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(124,184,155,0.62)',
    backgroundColor: 'rgba(124,184,155,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  createPostBtnText: {
    color: '#d1fae5',
    fontSize: 13,
    fontWeight: '800',
  },
  eventsTabRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(15,23,42,0.75)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 12,
    padding: 3,
    marginBottom: 14,
  },
  eventsTabBtn: {
    flex: 1,
    borderRadius: 9,
    paddingVertical: 9,
    alignItems: 'center',
  },
  eventsTabBtnActive: {
    backgroundColor: 'rgba(125,162,199,0.26)',
  },
  eventsTabText: {
    color: '#9ca3af',
    fontSize: 16,
    fontWeight: '700',
  },
  eventsTabTextActive: {
    color: '#f8fafc',
  },
  eventsListContainer: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 16,
    backgroundColor: 'rgba(10,14,24,0.82)',
    paddingHorizontal: 13,
    paddingVertical: 5,
    marginBottom: 12,
    height: 318,
  },
  eventsLoadingText: {
    color: '#93c5fd',
    fontSize: 14,
    fontWeight: '700',
    paddingTop: 6,
    paddingBottom: 2,
  },
  eventsEmptyText: {
    color: '#94a3b8',
    fontSize: 16,
    textAlign: 'center',
    paddingTop: 18,
  },
  eventRow: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 11,
  },
  eventDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.12)',
    width: '78%',
    alignSelf: 'center',
  },
  eventDateCol: {
    width: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    backgroundColor: 'rgba(2,6,23,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
  },
  eventDateMonth: {
    color: '#e5e7eb',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  eventDateDay: {
    color: '#f8fafc',
    fontSize: 31,
    lineHeight: 36,
    fontWeight: '800',
    marginVertical: 1,
  },
  eventDateDow: {
    color: '#9ca3af',
    fontSize: 13,
    fontWeight: '700',
  },
  eventInfoCol: {
    flex: 1,
    justifyContent: 'center',
  },
  eventTitle: {
    color: '#f8fafc',
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '700',
  },
  eventMeta: {
    color: '#cbd5e1',
    fontSize: 14,
    marginTop: 3,
  },
  eventRsvp: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },
  eventSourceLabel: {
    color: '#94a3b8',
  },
  eventStatusLive: {
    color: '#86efac',
  },
  eventStatusPassed: {
    color: '#fca5a5',
  },
  progressPostCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 14,
    backgroundColor: 'rgba(10,14,24,0.82)',
    padding: 14,
    marginBottom: 14,
  },
  progressPostHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressPostAuthor: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '700',
  },
  progressPostTime: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
  },
  progressPostCaption: {
    color: '#e2e8f0',
    fontSize: 16,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 10,
  },
  progressPostStatus: {
    color: '#93c5fd',
    fontSize: 13,
    fontWeight: '700',
    marginTop: -2,
    marginBottom: 8,
  },
  progressPostImage: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: 'rgba(30,41,59,0.7)',
    width: '100%',
    aspectRatio: 1,
    minHeight: 280,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  progressPostImageActual: {
    width: '100%',
    height: '100%',
  },
  progressPostImageText: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
  },
  createPostPreviewImage: {
    width: '100%',
    height: 144,
    borderRadius: 12,
    marginBottom: 12,
  },
  leaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    backgroundColor: 'rgba(15,23,42,0.35)',
  },
  leaderRank: {
    width: 28,
    color: '#86efac',
    fontSize: 19,
    fontWeight: '800',
  },
  leaderMid: {
    flex: 1,
    paddingHorizontal: 8,
  },
  leaderName: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '700',
  },
  leaderNote: {
    color: '#94a3b8',
    fontSize: 13,
    marginTop: 2,
  },
  leaderPts: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '700',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    position: 'relative',
    paddingTop: 12,
  },
  appHeader: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(148,163,184,0.28)',
    backgroundColor: '#0f172a',
    zIndex: 20,
    elevation: 20,
  },
  appHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
  },
  appHeaderSide: {
    width: 88,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  appHeaderSideRight: {
    justifyContent: 'flex-end',
  },
  appHeaderTitleWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  appHeaderTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.15,
    textAlign: 'center',
  },
  appHeaderSubtitle: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  appHeaderSubtitleMuted: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
  },
  appHeaderMenuBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(148,163,184,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(31,41,55,0.55)',
  },
  appHeaderAlertBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  appHeaderAlertBadge: {
    position: 'absolute',
    right: -4,
    top: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    backgroundColor: '#dc2626',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#0f172a',
  },
  appHeaderAlertBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 12,
  },
  appHeaderWeather: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  appHeaderWeatherText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 2,
    flexShrink: 1,
    minWidth: 0,
  },
  headerGreetingColumn: {
    flex: 1,
    minWidth: 0,
  },
  /** Same `gap` as `weatherStack`: primary line → secondary line (date→time, °F→condition). */
  headerDateStack: {
    marginTop: 0,
    gap: 2,
  },
  /** Tighter text box so date/time top lines up with the weather row (Android extra font padding). */
  headerDateLine: {
    includeFontPadding: false,
  },
  menuBtn: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 10,
  },
  menuLine: {
    width: 24,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#fafafa',
  },
  greeting: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '700',
  },
  alertBlock: {
    position: 'absolute',
    top: 30,
    left: '50%',
    width: 92,
    transform: [{ translateX: -46 }],
    alignItems: 'center',
  },
  alertIconWrap: {
    position: 'relative',
  },
  alertBadge: {
    position: 'absolute',
    right: -8,
    top: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#dc2626',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#111827',
  },
  alertBadgeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 17,
  },
  alertText: {
    color: '#eab308',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
    textAlign: 'center',
    width: '100%',
  },
  alertsModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,23,0.7)',
    paddingHorizontal: 14,
  },
  alertsModalCard: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: '#111827',
    padding: 12,
  },
  alertsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  alertsBackBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.26)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.7)',
  },
  alertsHeaderTextWrap: {
    flex: 1,
  },
  alertsTitle: {
    color: '#f8fafc',
    fontSize: 26,
    fontWeight: '800',
  },
  alertsSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 2,
    fontWeight: '600',
  },
  alertsMuteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginBottom: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.28)',
    backgroundColor: 'rgba(15,23,42,0.55)',
  },
  alertsMuteBtnText: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '600',
  },
  alertsEmptyCard: {
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.25)',
    borderRadius: 12,
    backgroundColor: 'rgba(15,23,42,0.45)',
    paddingVertical: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertsEmptyText: {
    color: '#cbd5e1',
    fontSize: 17,
    fontWeight: '700',
  },
  alertsCard: {
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.45)',
    borderRadius: 12,
    backgroundColor: 'rgba(127,29,29,0.22)',
    padding: 12,
    marginBottom: 10,
  },
  alertsCardTitle: {
    color: '#fecaca',
    fontSize: 17,
    fontWeight: '800',
  },
  alertsCardDetail: {
    color: '#e2e8f0',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  alertsCardSeverity: {
    color: '#fca5a5',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 7,
  },
  profileShowcaseBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,23,0.78)',
    paddingHorizontal: 14,
    paddingTop: 52,
    paddingBottom: 24,
  },
  profileShowcaseCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: '#0f172a',
    overflow: 'hidden',
  },
  profileShowcaseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.2)',
  },
  profileShowcaseBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(15,23,42,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileShowcaseHeaderText: {
    flex: 1,
  },
  profileShowcaseTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
  },
  profileShowcaseSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 2,
  },
  profileShowcaseScroll: {
    flex: 1,
  },
  profileAvatarWrap: {
    alignItems: 'center',
    paddingTop: 28,
    paddingBottom: 8,
  },
  profileAvatarRing: {
    width: 132,
    height: 132,
    borderRadius: 66,
    borderWidth: 3,
    borderColor: 'rgba(56,189,248,0.55)',
    backgroundColor: 'rgba(15,23,42,0.9)',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarImage: {
    width: 124,
    height: 124,
    borderRadius: 62,
  },
  profilePersonalityBlock: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 4,
  },
  profilePersonalityLabel: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  profilePersonalityCode: {
    color: '#f8fafc',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 4,
  },
  profilePersonalityName: {
    color: '#94a3b8',
    fontSize: 17,
    fontWeight: '600',
    marginTop: 4,
  },
  profileQuestionnaireBtn: {
    marginTop: 18,
    width: '100%',
    maxWidth: 320,
    alignSelf: 'center',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(56,189,248,0.45)',
    backgroundColor: 'rgba(14,165,233,0.12)',
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  profileQuestionnaireBtnTextWrap: {
    flex: 1,
  },
  profileQuestionnaireBtnTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '700',
  },
  profileQuestionnaireBtnSubtitle: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 3,
    lineHeight: 18,
  },
  profileShowcaseDivider: {
    height: 1,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 18,
    backgroundColor: 'rgba(148,163,184,0.35)',
  },
  profileExportSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
  },
  profileExportSectionLabel: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  profileExportOptionGroup: {
    gap: 8,
    marginBottom: 16,
  },
  profileExportOptionLabel: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 4,
  },
  profileExportSegmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileExportSegmentBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    backgroundColor: 'rgba(15,23,42,0.65)',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  profileExportSegmentBtnActive: {
    borderColor: 'rgba(56,189,248,0.65)',
    backgroundColor: 'rgba(14,165,233,0.18)',
  },
  profileExportSegmentBtnText: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '700',
  },
  profileExportSegmentBtnTextActive: {
    color: '#f8fafc',
  },
  profileExportPrimaryBtn: {
    marginTop: 4,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(56,189,248,0.45)',
    backgroundColor: 'rgba(14,165,233,0.18)',
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileExportPrimaryBtnDisabled: {
    opacity: 0.55,
  },
  profileExportPrimaryBtnText: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '800',
  },
  profileExportPrivacyText: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 12,
  },
  profileExportAppleHintText: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 10,
  },
  profileExportCustomRange: {
    gap: 10,
    marginTop: 4,
  },
  profileExportDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileExportDateLabel: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '700',
    width: 44,
  },
  profileExportDateBtn: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    backgroundColor: 'rgba(15,23,42,0.65)',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  profileExportDateBtnText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  profileExportDatePickerCard: {
    marginTop: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    backgroundColor: 'rgba(15,23,42,0.85)',
    overflow: 'hidden',
  },
  profileExportDatePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.2)',
  },
  profileExportDatePickerTitle: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '700',
  },
  profileExportDatePickerDone: {
    color: '#38bdf8',
    fontSize: 15,
    fontWeight: '800',
  },
  dataExportProgressBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(2,6,23,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  dataExportProgressCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: '#0f172a',
    paddingHorizontal: 20,
    paddingVertical: 22,
    alignItems: 'center',
  },
  dataExportProgressTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  dataExportProgressSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
  },
  profileBadgesSectionLabel: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    paddingHorizontal: 20,
  },
  profileBadgesSectionHint: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 16,
    paddingHorizontal: 20,
    lineHeight: 20,
  },
  profileBadgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    rowGap: 18,
    columnGap: 8,
    paddingBottom: 28,
    justifyContent: 'space-between',
  },
  profileBadgeCell: {
    width: '31%',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  profileBadgeCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 2,
    borderColor: 'rgba(56,189,248,0.55)',
    backgroundColor: 'rgba(14,165,233,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileBadgeCircleLocked: {
    borderColor: 'rgba(71,85,105,0.65)',
    backgroundColor: 'rgba(30,41,59,0.55)',
    opacity: 0.85,
  },
  profileBadgeGlyph: {
    fontSize: 36,
    textAlign: 'center',
    includeFontPadding: false,
  },
  profileBadgeGlyphLocked: {
    opacity: 0.4,
  },
  profileBadgeName: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 17,
    marginTop: 10,
    width: '100%',
  },
  profileBadgeNameLocked: {
    color: '#64748b',
  },
  weatherText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
  },
  weatherBlock: {
    alignItems: 'flex-end',
  },
  /** Column under header; keep condition tucked close to °F row (avoid extra gap stacking). */
  weatherStack: {
    alignItems: 'flex-end',
  },
  weatherTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  weatherSubText: {
    color: '#e5e7eb',
    fontSize: 12,
    lineHeight: 14,
    /** Pull label up under the icon/°F row; `gap` here was reading as too much space. */
    marginTop: -5,
    fontWeight: '500',
  },
  date: {
    color: '#e4e4e7',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 0,
  },
  dateTimeSub: {
    color: '#a1a1aa',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  scoreCard: {
    borderRadius: 18,
    borderColor: 'transparent',
    borderWidth: 0,
    padding: 14,
    backgroundColor: 'transparent',
    overflow: 'visible',
    minHeight: 220,
    shadowColor: '#ffffff',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  gaugeWrap: {
    position: 'absolute',
    top: -20,
    left: -20,
    right: -20,
  },
  scoreCenterStack: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingTop: 70,
  },
  scoreLabel: {
    color: '#52525b',
    fontSize: 10,
    letterSpacing: 1.9,
    fontWeight: '700',
    textAlign: 'center',
  },
  scoreHeart: {
    color: '#ef4444',
    textAlign: 'center',
    fontSize: 15,
    lineHeight: 15,
    fontWeight: '700',
    marginTop: -8,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    marginTop: 0,
  },
  score: {
    color: '#fff',
    fontSize: 56,
    lineHeight: 58,
    fontWeight: '700',
    includeFontPadding: false,
  },
  scoreUnit: {
    color: '#71717a',
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '500',
    marginLeft: 3,
  },
  scoreState: {
    color: '#facc15',
    letterSpacing: 4,
    fontWeight: '700',
    marginTop: 0,
    fontSize: 14,
    lineHeight: 16,
    textAlign: 'center',
  },
  scoreStateGood: {
    color: '#22c55e',
  },
  scoreStatePoor: {
    color: '#ef4444',
  },
  scoreSub: {
    color: '#71717a',
    marginTop: 0,
    fontSize: 11,
    lineHeight: 14,
    textAlign: 'center',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
    gap: 8,
  },
  glassCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 100,
    borderRadius: 12,
    borderColor: 'rgba(255,255,255,0.4)',
    borderWidth: 1,
    backgroundColor: 'transparent',
    padding: 11,
    overflow: 'hidden',
    shadowColor: '#ffffff',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 9,
  },
  dashboardMetricCard: {
    minHeight: 0,
  },
  metricLabel: {
    color: '#a1a1aa',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    minWidth: 0,
  },
  metricTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    minWidth: 0,
    gap: 6,
  },
  metricTitleLabel: {
    flex: 1,
  },
  metricValueWrap: {
    width: '100%',
    minWidth: 0,
    marginTop: 4,
    overflow: 'hidden',
  },
  metricValue: {
    color: '#fff',
    fontSize: 29,
    fontWeight: '700',
    width: '100%',
    minWidth: 0,
    includeFontPadding: false,
  },
  metricUnit: {
    color: '#71717a',
    fontSize: 10,
    fontWeight: '700',
    flexShrink: 0,
    includeFontPadding: false,
  },
  metricStatus: {
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
    width: '100%',
    minWidth: 0,
    includeFontPadding: false,
  },
  glassCardLarge: {
    borderRadius: 16,
    borderColor: 'rgba(255,255,255,0.38)',
    borderWidth: 1,
    backgroundColor: 'transparent',
    padding: 13,
    gap: 8,
    shadowColor: '#ffffff',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 0 },
    elevation: 9,
  },
  row: {
    flexDirection: 'row',
    gap: 8,
  },
  primaryBtn: {
    flex: 1,
    backgroundColor: '#2563eb',
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: 'center',
  },
  primaryBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  secondaryBtn: {
    flex: 1,
    borderColor: '#3f3f46',
    borderWidth: 1,
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: 'center',
  },
  secondaryBtnText: {
    color: '#a1a1aa',
    fontWeight: '700',
    fontSize: 13,
  },
  sectionLabel: {
    color: '#52525b',
    fontSize: 11,
    letterSpacing: 0.9,
    fontWeight: '700',
    marginTop: 0,
  },
  quickActionsSection: {
    gap: 14,
    marginBottom: 32,
  },
  quickActionsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  quickActionsCustomizeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexShrink: 0,
    backgroundColor: 'rgba(148,163,184,0.1)',
    borderColor: 'rgba(148,163,184,0.28)',
  },
  quickActionsCustomizeText: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  quickMetricsPickerBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(2,6,23,0.72)',
  },
  quickMetricsPickerCard: {
    maxHeight: '82%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.18)',
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 24,
  },
  quickMetricsPickerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  quickMetricsPickerHeaderText: {
    flex: 1,
    gap: 4,
  },
  quickMetricsPickerTitle: {
    color: '#f8fafc',
    fontSize: 20,
    fontWeight: '800',
  },
  quickMetricsPickerHint: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
  },
  quickMetricsPickerCloseBtn: {
    padding: 4,
  },
  quickMetricsPickerCount: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 8,
  },
  quickMetricsPickerScroll: {
    flexGrow: 0,
  },
  quickMetricsPickerSection: {
    marginBottom: 16,
  },
  quickMetricsPickerSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  quickMetricsPickerSectionAccent: {
    width: 4,
    height: 14,
    borderRadius: 2,
  },
  quickMetricsPickerSectionTitle: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  quickMetricsPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.14)',
    backgroundColor: 'rgba(15,23,42,0.45)',
    marginBottom: 8,
  },
  quickMetricsPickerRowSelected: {
    borderColor: 'rgba(125,162,199,0.45)',
    backgroundColor: 'rgba(125,162,199,0.12)',
  },
  quickMetricsPickerRowIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.5)',
  },
  quickMetricsPickerRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
  },
  quickMetricsPickerRowLabelSelected: {
    fontWeight: '800',
  },
  quickMetricsPickerDoneBtn: {
    marginTop: 8,
    borderRadius: 12,
    backgroundColor: '#7DA2C7',
    paddingVertical: 14,
    alignItems: 'center',
  },
  quickMetricsPickerDoneText: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  quickRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
  },
  quickItem: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gap: 9,
  },
  quickIcon: {
    width: 62,
    height: 62,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.42)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ffffff',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  quickIconGlyph: {
    color: '#a1a1aa',
    fontSize: 24,
    fontWeight: '700',
  },
  quickText: {
    color: '#71717a',
    fontSize: 13,
    fontWeight: '600',
    width: '100%',
    textAlign: 'center',
  },
  activityContainer: {
    marginTop: 4,
    borderRadius: 12,
    borderColor: 'rgba(255,255,255,0.36)',
    borderWidth: 1,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    overflow: 'hidden',
    shadowColor: '#ffffff',
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  activityItem: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 11,
    gap: 8,
    position: 'relative',
  },
  activityDivider: {
    position: 'absolute',
    right: 0,
    top: 8,
    bottom: 8,
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  activityLabel: {
    color: '#71717a',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  activityTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  activityTextStack: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 2,
  },
  activityValue: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  activityTrack: {
    width: '100%',
    height: 6,
    borderRadius: 999,
    backgroundColor: '#27272a',
    overflow: 'hidden',
    flexDirection: 'row',
  },
  activityFill: {
    height: 6,
    borderRadius: 999,
  },
  activityTrackRemainder: {
    height: 6,
    backgroundColor: 'transparent',
  },
  /** Clears the bottom tab bar (touch + paint order). `bottom` is set via `useAppChrome()`. */
  tabStackLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 50,
    elevation: 50,
    backgroundColor: '#0f172a',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(148,163,184,0.28)',
    overflow: 'visible',
    shadowColor: '#000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
  },
  bottomNavRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    overflow: 'visible',
  },
  navItem: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  navItemInner: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingTop: 4,
    paddingBottom: 4,
    paddingHorizontal: 4,
    borderRadius: 12,
    minWidth: 56,
  },
  navItemInnerActive: {
    backgroundColor: 'rgba(59,130,246,0.16)',
  },
  navCenterButton: {
    position: 'absolute',
    alignSelf: 'center',
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1e293b',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(148,163,184,0.35)',
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 12,
    zIndex: 60,
  },
  navCenterButtonActive: {
    borderWidth: 2,
    borderColor: '#60a5fa',
    shadowOpacity: 0.38,
  },
  navIconWrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIcon: {
    color: '#71717a',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
    textAlign: 'center',
  },
  navText: {
    color: '#71717a',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
    textAlign: 'center',
    width: '100%',
  },
  navActive: {
    color: '#60a5fa',
  },
  navCenterAlertBadge: {
    top: 2,
    right: 2,
  },
  navAlertBadge: {
    position: 'absolute',
    top: 0,
    right: 6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: '#dc2626',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#111827',
    zIndex: 2,
  },
  navAlertBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 13,
  },
  sidebarOverlay: {
    position: 'absolute',
    inset: 0,
    zIndex: 200,
    elevation: 200,
    flexDirection: 'row',
  },
  sidebarScrim: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  sidebarPanel: {
    width: 250,
    backgroundColor: '#0a0f1a',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255,255,255,0.18)',
    paddingTop: 56,
    paddingHorizontal: 14,
  },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sidebarTitle: {
    color: '#f3f4f6',
    fontSize: 26,
    fontWeight: '800',
  },
  sidebarClose: {
    color: '#f3f4f6',
    fontSize: 29,
    lineHeight: 29,
  },
  sidebarItem: {
    paddingVertical: 8,
    paddingHorizontal: 2,
    marginBottom: 6,
  },
  sidebarItemText: {
    color: '#e5e7eb',
    fontSize: 22,
    fontWeight: '700',
  },
  sidebarDivider: {
    height: 1,
    backgroundColor: 'rgba(148,163,184,0.25)',
    marginVertical: 8,
  },
  sidebarSection: {
    marginTop: 2,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 10,
    padding: 10,
  },
  sidebarSectionTitle: {
    color: '#e5e7eb',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 10,
    textDecorationLine: 'underline',
  },
  demoToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    minHeight: 52,
    paddingVertical: 10,
    marginBottom: 6,
  },
  demoToggleRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  demoToggleLabel: {
    color: '#d1d5db',
    fontSize: 18,
    flex: 1,
    fontWeight: '700',
  },
  demoTogglePill: {
    minWidth: 66,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  demoTogglePillActive: {
    backgroundColor: 'rgba(59,130,246,0.22)',
    borderColor: 'rgba(59,130,246,0.7)',
  },
  demoTogglePillText: {
    color: '#e5e7eb',
    fontSize: 16,
    fontWeight: '700',
  },
  demoTogglePillTextActive: {
    color: '#93c5fd',
  },
  demoDropdownBtn: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
    backgroundColor: 'rgba(15,23,42,0.45)',
  },
  demoDropdownText: {
    color: '#cbd5e1',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 16,
  },
  demoDropdownList: {
    marginTop: 2,
    marginLeft: 10,
  },
  demoHelperText: {
    marginTop: 10,
    color: '#9ca3af',
    fontSize: 14,
    fontWeight: '500',
  },
};

const LAYOUT_SCALE_KEYS = ['scoreCard', 'gaugeWrap', 'scoreCenterStack', 'scoreUnit', 'glassCard', 'grid'] as const;

export function getAppStyles(windowWidth: number) {
  const scaled = scaleStyleRecord(
    baseStyleDefinitions as Record<string, import('react-native').ViewStyle | import('react-native').TextStyle>,
    windowWidth,
  );
  return StyleSheet.create(scaleStyleKeysLayout(scaled, LAYOUT_SCALE_KEYS, windowWidth));
}
